# Generated by Django 3.2.8 on 2021-11-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0003_group_grouppermission_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='finishedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='startedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
