# Generated by Django 3.2.8 on 2021-12-07 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0026_alter_inventoryproduct_isopen'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('inCash', models.BooleanField(default=False)),
                ('isPortion', models.BooleanField(default=False)),
                ('portionAmount', models.IntegerField()),
                ('dueDate', models.IntegerField()),
                ('percentagePerDelay', models.DecimalField(decimal_places=3, max_digits=6)),
                ('percentageDiscount', models.DecimalField(decimal_places=3, max_digits=6)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayReceive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portionNumber', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('valueExtra', models.DecimalField(decimal_places=3, max_digits=10)),
                ('valueDiscount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('paymentDateFixed', models.DateTimeField()),
                ('paymentDateAccomplished', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.document')),
                ('paymentMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.paymentmethod')),
            ],
        ),
    ]
