# Generated by Django 3.2.8 on 2021-12-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_paymentmethodlog_payreceivelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='portionRegex',
            field=models.TextField(default='NA'),
        ),
    ]
