# Generated by Django 3.2.8 on 2021-10-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211031_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='isOpen',
            field=models.BooleanField(default=True),
        ),
    ]
