# Generated by Django 3.2.8 on 2021-10-31 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_documentproduct_isopen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='value',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
