# Generated by Django 3.2.8 on 2021-11-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_stock_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
