# Generated by Django 3.2.8 on 2021-11-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_stock_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
