# Generated by Django 3.2.8 on 2021-11-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_stockmovement_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='isValid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='margin',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='deposit',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('key', 'documentType')},
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('name', 'identifier', 'identifierType', 'entityType')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name',)},
        ),
    ]
