# Generated by Django 3.2.8 on 2021-11-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20211102_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentproduct',
            name='isNew',
            field=models.BooleanField(default=True),
        ),
    ]
