# Generated by Django 3.2.8 on 2021-11-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20211123_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='phone2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='phone1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='phone2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='phone1',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='phone2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
