# Generated by Django 3.2.8 on 2021-11-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20211123_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='deliveryValue',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
