# Generated by Django 3.2.8 on 2021-11-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_document_sendmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('documentType', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saida')], max_length=3)),
                ('stock', models.BooleanField(default=False)),
                ('product', models.BooleanField(default=False)),
                ('financial', models.BooleanField(default=False)),
                ('order', models.BooleanField(default=False)),
                ('updateCost', models.BooleanField(default=False)),
                ('createPrice', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
