# Generated by Django 3.2.8 on 2021-11-30 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_documentfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(default=99999, on_delete=django.db.models.deletion.CASCADE, to='shop.documentfolder'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('key', 'deposit', 'entity', 'folder')},
        ),
        migrations.RemoveField(
            model_name='document',
            name='documentType',
        ),
    ]
