# Generated by Django 3.2.8 on 2021-11-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20211130_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='isOpen',
            field=models.BooleanField(default=True),
        ),
    ]
