# Generated by Django 3.2.8 on 2021-12-04 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_inventory_isopen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorylog',
            old_name='entity',
            new_name='inventory',
        ),
    ]
