# Generated by Django 3.2.8 on 2021-12-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_inventory_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryproduct',
            name='valueBefore',
            field=models.IntegerField(default=0),
        ),
    ]
