# Generated by Django 3.2.8 on 2021-12-07 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_paymentmethodlog_payreceivelog'),
        ('shop', '0027_documentfolderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='paymentMethod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backoffice.paymentmethod'),
            preserve_default=False,
        ),
    ]
