# Generated by Django 3.2.8 on 2021-12-18 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_document_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('productChild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productChild', to='shop.product')),
                ('productMain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productMain', to='shop.product')),
            ],
            options={
                'unique_together': {('productMain', 'productChild')},
            },
        ),
    ]
