# Generated by Django 3.2.8 on 2021-12-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_productkit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('NOR', 'Normal'), ('KIT', 'Kit')], default='NOR', max_length=3),
        ),
    ]
