# Generated by Django 3.2.8 on 2021-11-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20211123_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='crontab',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executionlog',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executionmanual',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
